#Use the official Node.js image as the base image
FROM node:20-slim

#Set the working directory
WORKDIR /usr/src/app

#Copy nestjs module dependencies file
#A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

#Install app dependencies
RUN npm install

#Bundle app source
#Copy all source code to working directory
COPY . .

#Creates a "dist" folder with the production build
RUN npm run build

#Expose the port on which the app will run
EXPOSE 3333

#Start the server using the production build
CMD npm run start:prod
