# Base image
FROM node:20-slim

# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package.json ./

# Install app dependencies
RUN npm install

# Bundle app source

# Expose the port on which the app will run
# was port 5173 in main.ts
EXPOSE 5173

# Start the server using the production build
# Create app directory
WORKDIR /usr/src/app/LineCMS_Project
COPY LineCMS_Project .

RUN rm -rf node_modules
RUN rm package-lock.json
RUN npm install

CMD npm run dev -- --host 0.0.0.0

